Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket
    Default: react-app-bucket-unique

Resources:
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: react-app-bucket-unique
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false


Outputs:
  WebsiteURL:
    Description: URL of the static website
    Value: !GetAtt ReactAppBucket.WebsiteURL
