Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket
    Default: react-website-9535-login

Resources:
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

Outputs:
  WebsiteURL:
    Description: URL of the static website
    Value: !GetAtt ReactAppBucket.WebsiteURL
